# Generated by Django 3.0.3 on 2020-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_user', models.CharField(max_length=100)),
                ('windowsuptodate', models.CharField(choices=[('updated', 'Updated'), ('not updated', 'Not Updated')], max_length=100)),
                ('hardisk', models.CharField(choices=[('normal', 'Normal'), ('critical', 'Critical')], max_length=100)),
                ('outlook', models.CharField(choices=[('working', 'Working'), ('notworking', 'Not Working')], max_length=100)),
                ('eventviewer', models.CharField(choices=[('error', 'Error'), ('no error', 'No Error'), ('password reqired', 'Password Required'), ('power off', 'Power Off'), ('office 2016 licensing', 'office 2016 licensing')], max_length=100)),
                ('jabradirect', models.CharField(choices=[('up to date', 'Up to date'), ('not updated', 'Not Updated')], max_length=100)),
                ('softwareupdatetodate', models.CharField(choices=[('up to date', 'Up to date'), ('not updated', 'Not Updated')], max_length=100)),
                ('pdriveaccess', models.CharField(choices=[('accessible', 'Accessible'), ('notaccessible', 'Not Accessible')], max_length=100)),
                ('windowsactivation', models.CharField(choices=[('activated', 'Activated'), ('notactivated', 'Not Activated')], max_length=100)),
                ('updated', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
