# Generated by Django 3.0.3 on 2020-03-20 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrequirementmodel',
            name='reqpname',
        ),
    ]
