# Generated by Django 3.0.3 on 2020-03-20 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0003_systemupdatemodel_orgname'),
        ('clientdashboard', '0002_remove_systemrequirementmodel_reqpname'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrequirementmodel',
            name='reqpname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supportteamapp.OrgInsertion'),
            preserve_default=False,
        ),
    ]
