# Generated by Django 3.0.3 on 2020-03-20 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnsiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('cperson', models.CharField(max_length=100, null=True)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('appby', models.CharField(max_length=100, null=True)),
                ('workdate', models.DateField(null=True)),
                ('worktimein', models.TimeField(null=True)),
                ('worktimeout', models.TimeField(null=True)),
                ('workdone', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('proname', models.CharField(blank=True, max_length=100, null=True)),
                ('serialno', models.IntegerField(blank=True, null=True)),
                ('proappby', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgInsertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(max_length=100)),
                ('organizationmail', models.CharField(max_length=100)),
                ('organizationaddr', models.CharField(max_length=100)),
                ('organizationphone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemUpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysname', models.CharField(max_length=150)),
                ('hddspace', models.CharField(max_length=150)),
                ('ramsize', models.CharField(max_length=150)),
                ('winstatus', models.CharField(max_length=150)),
                ('softwares', models.CharField(max_length=1000)),
                ('healthstatus', models.CharField(max_length=150)),
                ('powerstatus', models.CharField(max_length=150)),
                ('issues', models.CharField(blank=True, max_length=1000, null=True)),
                ('ongoingissues', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('orgname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportteamapp.OrgInsertion')),
            ],
        ),
    ]
