# Generated by Django 3.0.3 on 2020-03-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0003_systemupdatemodel_orgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdatemodel',
            name='eventlog',
            field=models.FileField(default='', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
