# Generated by Django 3.0.3 on 2020-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0004_systemupdatemodel_eventlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemupdatemodel',
            name='eventlog',
        ),
        migrations.AddField(
            model_name='systemupdatemodel',
            name='department',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
