# Generated by Django 3.0.3 on 2020-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0005_auto_20200321_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsitemodel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onsitemodel',
            name='purpose',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='onsitemodel',
            name='workdone',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
