# Generated by Django 3.0.3 on 2020-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0006_auto_20200322_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemupdatemodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
