# Generated by Django 3.0.3 on 2020-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportteamapp', '0008_auto_20200406_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemupdatemodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
